# config.yaml
mqttBrokerUrl: mqtt://localhost:1883
ingestPort: 3000

topic: upstream/containers
batchSize: 50
mtuBytes: 800
flushIntervalMs: 30000

brotli:
  quality: 5
  mode: text   # valid values: text, generic, font
