version: '3.8'

services:
  # ========================================
  # ENCODER SERVICE (Local Machine)
  # ========================================
  # Uncomment this section for local machine deployment
  esp32-encoder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: esp32-encoder-local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DECODER_URL=http://172.25.1.78:3001
    restart: unless-stopped
    networks:
      - esp32-network
    command: ["node", "esp32-encoder.js"]

  # ========================================
  # DECODER SERVICE (VM)
  # ========================================
  # Uncomment this section for VM deployment
  # esp32-decoder:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: esp32-decoder-vm
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=3000
  #     - MOBIUS_URL=http://172.25.1.78:7579/Mobius/Natesh/NateshContainer?ty=4
  #     - MOBIUS_ORIGIN=Natesh
  #   restart: unless-stopped
  #   networks:
  #     - esp32-network
  #   command: ["node", "esp32-cbor-decoder.js"]

networks:
  esp32-network:
    driver: bridge 