version: '3.8'

services:
  # Master Node (Local Machine)
  astrocast-master:
    build:
      context: .
      dockerfile: Dockerfile.astrocast
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_MODE=master
      - NODE_ENV=production
      - PORT=3000
      - SLAVE_URL=http://172.25.1.78:3001/api/receive-compressed
    restart: unless-stopped
    networks:
      - astrocast-local-network

networks:
  astrocast-local-network:
    driver: bridge 