version: '3.8'

services:
  # ========================================
  # MASTER NODE CONFIGURATION (Local Machine)
  # ========================================
  # Uncomment this section for master node deployment
  astrocast-master:
    build:
      context: .
      dockerfile: Dockerfile.astrocast
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_MODE=master
      - NODE_ENV=production
      - PORT=3000
      - SLAVE_URL=http://172.25.1.78:3001/api/receive-compressed
    restart: unless-stopped
    networks:
      - astrocast-local-network

  # ========================================
  # SLAVE NODE CONFIGURATION (VM)
  # ========================================
  # Uncomment this section for slave node deployment
  # astrocast-slave:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.astrocast
  #   ports:
  #     - "3001:3000"
  #   volumes:
  #     - slave_data:/app/data
  #   environment:
  #     - NODE_MODE=slave
  #     - NODE_ENV=production
  #     - PORT=3000
  #     - MOBIUS_URL=http://172.25.1.78:7579/Mobius/Natesh/NateshContainer?ty=4
  #   restart: unless-stopped
  #   networks:
  #     - astrocast-local-network

volumes:
  slave_data:
    driver: local

networks:
  astrocast-local-network:
    driver: bridge 