version: '3.8'

services:
  # Master Node Configuration (Local Machine)
  # Uncomment this section for master node
  maritime-master:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_MODE=master
      - SLAVE_URL=http://172.25.1.78:3001/api/receive-compressed
      - PORT=3000
    restart: unless-stopped

  # Slave Node Configuration (VM)
  # Uncomment this section for slave node  
  # maritime-slave:
  #   build: .
  #   ports:
  #     - "3001:3000"
  #   volumes:
  #     - slave_data:/app/data
  #   environment:
  #     - NODE_MODE=slave
  #     - MOBIUS_URL=http://172.25.1.78:7579/Mobius/Natesh/NateshContainer?ty=4
  #     - PORT=3000
  #   restart: unless-stopped

volumes:
  slave_data: 